### PR TITLE
Update boards.yml

### PR DESCRIPTION
**Pull request by MarcAZ81**
Adding SolidRun Clearfog Pro A1 router board.

### CODE REVIEW

**Comment by AndrewMargarit** [comment]
That doesn't look right.

```lan_wan:  ["eth0", "eth1", "eth2", "ifb0", "ifb1", "lan1", "lan2", "lan3", "lan4", "lan4", "lan5", "lan6"]```
That board has 1 dedicated WAN port and a 4 port switch correct?

What eth is used for the WAN and which for the LAN side?
Also is there a switch config in the network?

https://github.com/mylittletony/SocketMan/wiki/Adding-a-board-profile

**Comment by MarcAZ81** [comment]
Hi Andrew,WAN can be :eth2 (ethernet)eth1 (ftth)wwan0 (lte)There’s also a LAN switch onboard :lan1lan2lan3lan4lan5lan6And two mini-PCIe slots for WiFi modules :wlan0wlan1Le 30 novembre 2017 à 17:07, Andrew Margarit <notifications@github.com> a écrit :That doesn't look right.lan_wan: ["eth0", "eth1", "eth2", "ifb0", "ifb1", "lan1", "lan2", "lan3", "lan4", "lan4", "lan5", "lan6"] That board has 1 dedicated WAN port and a 4 port switch correct?What eth is used for the WAN and which for the LAN side? Also is there a switch config in the network?https://github.com/mylittletony/SocketMan/wiki/Adding-a-board-profile—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by MarcAZ81** [comment]
Please see those logs taken from the socketman install. Apparently there's some problems during it, but the deamon is responding :root@OpenWrt:~# opkg install curlPackage curl (7.50.0-1) installed in root is up to date.root@OpenWrt:~# curl -k https://raw.githubusercontent.com/AndrewMargarit/socketman-installer/master/install | ash % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed100 1262 100 1262 0 0 5413 0 --:--:-- --:--:-- --:--:-- 5633 % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed100 168 0 168 0 0 2730 0 --:--:-- --:--:-- --:--:-- 5419curl: (6) Couldn't resolve host 'edge'grep: edge/mvebu: No such file or directoryDownloading http://downloads.openwrt.org/snapshots/trunk/mvebu/generic/packages/base/Packages.gz.Updated list of available packages in /var/opkg-lists/designated_driver_base.Downloading http://downloads.openwrt.org/snapshots/trunk/mvebu/generic/packages/base/Packages.sig.Signature check passed.Downloading http://downloads.openwrt.org/snapshots/trunk/mvebu/generic/packages/kernel/Packages.gz.Updated list of available packages in /var/opkg-lists/designated_driver_kernel.Downloading http://downloads.openwrt.org/snapshots/trunk/mvebu/generic/packages/kernel/Packages.sig.Signature check passed.Downloading http://downloads.openwrt.org/snapshots/trunk/mvebu/generic/packages/telephony/Packages.gz.Updated list of available packages in /var/opkg-lists/designated_driver_telephony.Downloading http://downloads.openwrt.org/snapshots/trunk/mvebu/generic/packages/telephony/Packages.sig.Signature check passed.Downloading http://downloads.openwrt.org/snapshots/trunk/mvebu/generic/packages/packages/Packages.gz.Updated list of available packages in /var/opkg-lists/designated_driver_packages.Downloading http://downloads.openwrt.org/snapshots/trunk/mvebu/generic/packages/packages/Packages.sig.Signature check passed.Downloading http://downloads.openwrt.org/snapshots/trunk/mvebu/generic/packages/routing/Packages.gz.Updated list of available packages in /var/opkg-lists/designated_driver_routing.Downloading http://downloads.openwrt.org/snapshots/trunk/mvebu/generic/packages/routing/Packages.sig.Signature check passed.Downloading http://downloads.openwrt.org/snapshots/trunk/mvebu/generic/packages/luci/Packages.gz.Updated list of available packages in /var/opkg-lists/designated_driver_luci.Downloading http://downloads.openwrt.org/snapshots/trunk/mvebu/generic/packages/luci/Packages.sig.Signature check passed.Downloading http://downloads.openwrt.org/snapshots/trunk/mvebu/generic/packages/management/Packages.gz.Updated list of available packages in /var/opkg-lists/designated_driver_management.Downloading http://downloads.openwrt.org/snapshots/trunk/mvebu/generic/packages/management/Packages.sig.Signature check passed.Unknown package 'socketman'.Package coova-chilli (1.3.0+20141128-4) installed in root is up to date.Collected errors: * opkg_install_cmd: Cannot install package socketman. % Total % Received % Xferd Average Speed Time Time Time Current Dload Upload Total Spent Left Speed100 2226 100 2226 0 0 2954 0 --:--:-- --:--:-- --:--:-- 2991All Doneroot@OpenWrt:~# ps | grep socketman30152 root 1208 S grep socketmanLe 1 décembre 2017 à 09:13, Marc Amstoutz <marc@ozcom.fr> a écrit :Hi Andrew,WAN can be :eth2 (ethernet)eth1 (ftth)wwan0 (lte)There’s also a LAN switch onboard :lan1lan2lan3lan4lan5lan6And two mini-PCIe slots for WiFi modules :wlan0wlan1Le 30 novembre 2017 à 17:07, Andrew Margarit <notifications@github.com> a écrit :That doesn't look right.lan_wan: ["eth0", "eth1", "eth2", "ifb0", "ifb1", "lan1", "lan2", "lan3", "lan4", "lan4", "lan5", "lan6"] That board has 1 dedicated WAN port and a 4 port switch correct?What eth is used for the WAN and which for the LAN side? Also is there a switch config in the network?https://github.com/mylittletony/SocketMan/wiki/Adding-a-board-profile—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by AndrewMargarit** [comment]
That's because we don't have a packaged candidate for OpenWRT. Just for LEDE.
We can work on that bit after.

Back on the board - Can you paste in here a working network config?

**Comment by MarcAZ81** [comment]
Please find bellow my network configs (lan & wireless) :root@OpenWrt:~# cat /etc/config/networkconfig interface 'loopback' option ifname 'lo' option proto 'static' option ipaddr '127.0.0.1' option netmask '255.0.0.0'config globals 'globals' option ula_prefix 'fd69:abde:92ed::/48'config interface 'lan' option type 'bridge' option ifname 'eth0 eth1' option proto 'static' option ipaddr '192.168.1.1' option netmask '255.255.255.0' option ip6assign '60'config interface 'wan' option ifname 'eth2' option proto 'dhcp'config interface 'wan6' option ifname 'eth2' option proto 'dhcpv6'config interface 'wlan0' option ifname 'wlan0' option proto 'static' option ipaddr '172.16.0.1' option netmask '255.255.255.0'config interface 'wlan1' option ifname 'wlan1' option proto 'static' option ipaddr '172.17.0.1' option netmask '255.255.255.0'config interface 'wwan' option ifname 'wwan0' option proto 'dhcp'root@OpenWrt:~# cat /etc/config/wirelessconfig wifi-device 'radio0' option type 'mac80211' option hwmode '11a' option path 'soc/soc:pcie-controller/pci0000:00/0000:00:02.0/0000:01:00.0' option country 'FR' option channel 'auto'config wifi-iface option device 'radio0' option mode 'ap' option encryption 'none' option network 'wlan0' option isolate '1' option ssid 'Guest'config wifi-device 'radio1' option type 'mac80211' option path 'soc/soc:pcie-controller/pci0000:00/0000:00:03.0/0000:02:00.0' option channel '10' option hwmode '11g' option country 'FR' option htmode 'HT40'config wifi-iface option device 'radio1' option mode 'ap' option encryption 'none' option network 'wlan1' option isolate '1' option ssid 'Guest'Le 1 décembre 2017 à 11:07, Andrew Margarit <notifications@github.com> a écrit :That's because we don't have a packaged candidate for OpenWRT. Just for LEDE. We can work on that bit after.Back on the board - Can you paste in here a working network config?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by AndrewMargarit** [comment]
let me see if I got this one right.

eth2 - WAN
eth0 and eth1 are the 4 ports on the switch?

radio0 - 5ghz radio ( is it 11AC ? )
radio1 - 2.4


Also, are you using a wireless uplink?

**Comment by MarcAZ81** [comment]
eth2 is currently the Ethernet WAN, I gave this MAC address for device MACI got 6 LAN ports on the router board for switching, it's lan1 to lan6wlan0 is for 5Ghzwlan1 is for 2.4wwan0 is for LTE WANLe 1 décembre 2017 à 11:36, Andrew Margarit <notifications@github.com> a écrit :let me see if I got this one right.eth2 - WAN eth0 and eth1 are the 4 ports on the switch?radio0 - 5ghz radio ( is it 11AC ? ) radio1 - 2.4Also, are you using a wireless uplink?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Review by AndrewMargarit — APPROVED** [review]

**Pull request merged**
