### PR TITLE
make sure curl global init and cleanup are called only once

### PR DESCRIPTION
**Pull request by mbecks**

### CODE REVIEW

**Comment by simonmorley** [comment]
@mbecks any chance you tested this with valgrind on debian etc???

**Comment by mbecks** [comment]
I just tested on OpenWRT CC and compiled on my local arch linux machine.

**Comment by simonmorley** [comment]
Would you mind running with valgrind please:

```
make clean; make && valgrind --leak-check=full ./socketman --config=/etc/config.json
```

You should expect some errors from mosquitto but no other leaks. I seem to remember having issues with this before, hence the overkill..

Thanks for fixing though :)

**Comment by mbecks** [comment]
It's showing a definite leak in mosquitto and in getaddrinfo and a possible leak resulting from a call to curl_easy_perform. No other errors.

**Comment by simonmorley** [comment]
Ok, thanks. I'll run locally over the weekend for a couple :)

**Pull request merged**
